### ISSUE TITLE
Try or Download

### ISSUE THREAD

**Issue by TheGeeKing** [CharlieS1103/spicetify-marketplace#10]
A little try button that injects using jsdelivr method and a download button that download locally the .js and will inject from there if not disabled

as discussed:
https://canary.discord.com/channels/842219447716151306/842819014941212682/892456113381974117
https://canary.discord.com/channels/842219447716151306/842819014941212682/892455076617138186
https://canary.discord.com/channels/842219447716151306/842819014941212682/892439466646593556

**Comment by theRealPadster** [comment]
It's all script injection, so not relevant anymore
