### ISSUE TITLE
Create a theme that can be used to revert to the default Spotify theme

### ISSUE THREAD

**Issue by cander824** [CharlieS1103/spicetify-marketplace#108]
Versions:
MacOS 12.2 Beta (21D5039d)
Spotify for macOS (Intel) 1.1.77.643.g3c4c6fc6
Spicetify v2.8.4 + [Marketplace v0.1.0-beta](https://github.com/CharlieS1103/spicetify-marketplace/releases/tag/v0.1-beta)

Within the Spicetify marketplace, it would be great to have a button to revert to stock Spotify. Note: I wouldn't want a button that would invoke the cli command of `spicetify backup apply` (as detailed [here](https://spectrum.chat/spicetify/general/how-to-delete-it~3ce8d647-233e-47b2-b5b3-b8f7a41d6122) where it says to do this to reset to the default Spotify theme). I want a button to fully reinstall Spotify to stock appearance.

**Comment by theRealPadster** [comment]
There is a trash icon when you hover over the currently installed theme. You can remove it, which should remove any customizations related to that theme and leave you with your stock Spotify theme. The only exception is if you have a Spicetify theme installed and in use via local files and your config_xpui.ini, in which case it would revert to _that_ theme. 

Or are you wanting a button to remove Spicetify completely? That would be outside the scope of Marketplace (and I don't think possible from within Spotify itself).

**Comment by CharlieS1103** [comment]
@theRealPadster i mean we could probs do it.

**Comment by theRealPadster** [comment]
> @theRealPadster i mean we could probs do it.

You can't run OS commands and remove files etc from the web browser/Spotify app

**Comment by CharlieS1103** [comment]
Yeah wouldn't we not need to? Couldn't we just remove the theme css and then add back the default colors as spicetify colors?

**Comment by theRealPadster** [comment]
I'm not sure what the issue is specifically for. The other thing to account for is that spicetify already themes the UI by default, so uninstalling the marketplace theme would show the default spicetify one, not Spotify. Unless there is a way to somehow remove the spicetify styling

**Comment by CharlieS1103** [comment]
@theRealPadster I mean all in all, this doesn't seem like something most people would want added
