### ISSUE TITLE
Rating tool tip when extensions are from same repo

### ISSUE THREAD

**Issue by TheGeeKing** [CharlieS1103/spicetify-marketplace#14]
Add a tool tip "this rating might not reflect this extension" on rating when extensions come from the same repo as it will have the same stars repo but might not be as good as it is rated.

https://discord.com/channels/842219447716151306/842819014941212682/894004924025819186

**Comment by CharlieS1103** [comment]
Will instead be patched by implementing stars as an internal feature.
