### ISSUE TITLE
Add handling for when extension does not have a readme

### ISSUE THREAD

**Issue by CharlieS1103** [CharlieS1103/spicetify-marketplace#30]
Can use the notification popup that spotify uses whenever a song can't be played.

**Comment by theRealPadster** [comment]
What does this look like? Is there a Spicetify method for that, or just the Popup we're using for other stuff?

**Comment by theRealPadster** [comment]
@CharlieS1103 ^ ? I could do this at some point or I feel like it's something you'd be able to tackle as well.

**Comment by CharlieS1103** [comment]
@theRealPadster working on themes rn, it actually seems fairly achievable for the next release.

**Comment by theRealPadster** [comment]
Fixed in 8627656
