### ISSUE TITLE
Marketplace Navbar Render Problem

### ISSUE THREAD

**Issue by ohitstom** [CharlieS1103/spicetify-marketplace#72]
**Describe the bug**
Marketplace navbar boundaries incorrectly set.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Spicetify
2. Install Spotify
3. Install marketplace

**Expected behaviour**
Correctly bounded navbar button

**Screenshots**
![image](https://user-images.githubusercontent.com/22730962/144725650-9157dc20-1c60-4153-8041-884432640be4.png)
![image](https://user-images.githubusercontent.com/22730962/144725656-fec5af80-266f-44a6-a0ba-0d4312706948.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Spicetify version: 2.8.3
 - Spotify version: 1.1.72.439.gc253025e
 - Marketplace version: Latest

**Comment by CharlieS1103** [comment]
@ohitstom We can close this issue correct?

**Comment by ohitstom** [comment]
yse
