### ISSUE TITLE
Pressing load more repeats stuff already there

### ISSUE THREAD

**Issue by niruvibes** [CharlieS1103/spicetify-marketplace#76]
**Describe the bug**
When clicking the "load more button", marketplace will just show the same extensions as before

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to marketplace
2. Load more
3. Scroll down

**Expected behaviour**
Extensions that have not been shown already to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/67180137/146140241-b27a6540-4157-443e-9cc7-342bd5c59b6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Spicetify version: The latest one idk number
 - Spotify version: 1.1.70
 - Marketplace version: latest one, idk number

**Additional context**

**Comment by theRealPadster** [comment]
@niruvibes Can you pull the latest from the main branch and see if this is resolved for you?

**Comment by theRealPadster** [comment]
I had this happen. Saved the complete log. I'm guessing it has something to do with the "Parsed -171/29 extensions" and then "Parsed 29/29 extensions" bit. 

https://pastebin.com/raw/bGEAQL9A
